development:
  adapter: postgresql
  encoding: utf8
  username: 
  password: 
  database: gallery_dev

test:
  adapter: postgresql
  encoding: utf8
  username:
  password:
  database: gallery_test

production:
  adapter: postgresql
  encoding: utf8
  username: 
  password: 
  database: gallery_prod