:output:
  AdminUser:
    :options:
      :fields:
      - id
      - email
      - created_at
      - updated_at
  Category:
    :options:
      :fields:
      - id
      - name
      - images_count
      - created_at
  Comment:
    :options:
      :fields:
      - id
      - body
      - image_id
      - user_id
      - created_at
  Event:
    :options:
      :fields:
      - id
      - user_id
      - eventable_type
      - eventable_id
      - created_at
  Image:
    :options:
      :fields:
      - id
      - url
      - comments_count
      - likes_count
      - category_id
      - created_at
  Like:
    :options:
      :fields:
      - id
      - user_id
      - image_id
      - created_at
  Message:
    :options:
      :fields:
      - id
      - body
      - user_id
      - created_at
  Navigation:
    :options:
      :fields:
      - id
      - url
  Subscribe:
    :options:
      :fields:
      - id
      - user_id
      - category_id
      - created_at
  User:
    :options:
      :fields:
      - id
      - nickname
      - email
      - created_at
      - last_sign_in_at
      - provider
      - avatar


